# Generated by Django 4.0.2 on 2022-03-01 15:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('laboratory', models.CharField(max_length=100)),
                ('application_mode', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccines',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('laboratory', models.CharField(max_length=100)),
                ('application_mode', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='pets',
            old_name='id_pert',
            new_name='id',
        ),
        migrations.CreateModel(
            name='PetVaccines',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('applicationDate', models.DateField()),
                ('doses_per_application', models.IntegerField()),
                ('time_between_doses', models.IntegerField()),
                ('expires_on', models.DurationField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.vaccines')),
            ],
        ),
        migrations.CreateModel(
            name='PetMedicines',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('applicationDate', models.DateField()),
                ('doses_per_application', models.IntegerField()),
                ('time_between_doses', models.IntegerField()),
                ('expires_on', models.DurationField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.medicines')),
            ],
        ),
        migrations.AlterField(
            model_name='pets',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user'),
        ),
    ]
