# Generated by Django 4.0.2 on 2022-03-14 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_medicines_user_vaccines_rename_id_pert_pets_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='haveMedicines',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.petmedicines'),
        ),
    ]
