# Generated by Django 4.0.2 on 2022-03-14 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_pets_havemedicines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pets',
            name='haveMedicines',
        ),
        migrations.RemoveField(
            model_name='pets',
            name='haveVaccines',
        ),
        migrations.AddField(
            model_name='petmedicines',
            name='pet_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.pets'),
        ),
    ]
