# Generated by Django 4.0.2 on 2022-03-15 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_pets_havemedicines_remove_pets_havevaccines_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petmedicines',
            name='pet_id',
        ),
        migrations.AddField(
            model_name='pets',
            name='haveMedicines',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.petmedicines'),
        ),
        migrations.AddField(
            model_name='pets',
            name='haveVaccines',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='petmedicines',
            name='medicine',
        ),
        migrations.AddField(
            model_name='petmedicines',
            name='medicine',
            field=models.ManyToManyField(to='backend.Medicines'),
        ),
    ]
