# Generated by Django 4.0.2 on 2022-03-15 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_petmedicines_pet_id_pets_havemedicines_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='haveMedicines',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.petmedicines'),
        ),
    ]
